### ISSUE TITLE
Problème de compilation sur projet propre + Identifier la version dans le fichier readme pour être certain du checkout

### ISSUE THREAD

**Issue by 0219-PORTERT** [0219-PORTERT/OUSOFT-0003#7]
Après avoir chargé la branche DEV je n'ai pas pu lancer le debug car il ne trouvait pas le fichier main.cpp (image_1). J'ai donc rebuildé le projet, mais 7 erreurs (image_2). Après avoir supprimé le fichier main.c (et non pas main.cpp) j'ai réussi à rebuildé (image_3) et débuger le projet.

![image_1](https://user-images.githubusercontent.com/63602470/81149792-2c980400-8f7f-11ea-80c9-8f048db16360.PNG)

![image_2](https://user-images.githubusercontent.com/63602470/81149795-2d309a80-8f7f-11ea-8a2d-c37dc26a7625.PNG)

![image 3](https://user-images.githubusercontent.com/63602470/81149790-2ace4080-8f7f-11ea-8d68-effcb5db0a05.PNG)

**Comment by 0219-PORTERT** [comment]
J'aurais peut être dû faire deux issues

**Comment by jikagq** [comment]
oui effectivement mais pas grave

**Comment by jikagq** [comment]
à retester une fois tous les fichiers du projet marqué en suivi

**Comment by jikagq** [comment]
OK une fois tous les fichiers ajoutés au projet
