### ISSUE TITLE
Pas de passage du debugger dans les catchs d'exception

### ISSUE THREAD

**Issue by 0219-PORTERT** [0219-PORTERT/OUSOFT-0003#8]
Je n'ai pas vu le passage du debugger dans le catch de l'exception 

![image](https://user-images.githubusercontent.com/63602470/81152762-89e18480-8f82-11ea-80a7-19f1c5cb158f.png)

**Comment by jikagq** [comment]
![ex1](https://user-images.githubusercontent.com/12010824/81155527-548a6600-8f85-11ea-84e0-0852bcb2f20a.PNG)
![ex2](https://user-images.githubusercontent.com/12010824/81155530-5522fc80-8f85-11ea-96e1-ea1539cbd904.PNG)
![ex3](https://user-images.githubusercontent.com/12010824/81155533-55bb9300-8f85-11ea-9dd2-919bf777850d.PNG)

Est-ce que les flags sont activés ?
